### ISSUE TITLE
Symfony conflict version

### ISSUE THREAD

**Issue by paulovitorbal** [Jorijn/ynab-bunq-connector-bundle#1]
I created a new symfony project:

`composer create-project symfony/skeleton:3.4 bunq-ynab`

And when I try to require your package:

> ➜
>  composer require jorijn/ynab-bunq-connector-bundle
> Using version ^1.0 for jorijn/ynab-bunq-connector-bundle
> ./composer.json has been updated
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - Installation request for __root__ No version set (parsed as 1.0.0) -> satisfiable by __root__[No version set (parsed as 1.0.0)].
>     - jorijn/ynab-bunq-connector-bundle v1.0.0 requires symfony/symfony 3.4.* -> satisfiable by symfony/symfony[v3.4.0, v3.4.1, v3.4.10, v3.4.11, v3.4.12, v3.4.13, v3.4.14, v3.4.2, v3.4.3, v3.4.4, v3.4.5, v3.4.6, v3.4.7, v3.4.8, v3.4.9].
>     - symfony/symfony v3.4.0 conflicts with __root__[No version set (parsed as 1.0.0)].
>     - symfony/symfony v3.4.1 conflicts with __root__[No version set (parsed as 1.0.0)].
>     - symfony/symfony v3.4.10 conflicts with __root__[No version set (parsed as 1.0.0)].
>     - symfony/symfony v3.4.11 conflicts with __root__[No version set (parsed as 1.0.0)].
>     - symfony/symfony v3.4.12 conflicts with __root__[No version set (parsed as 1.0.0)].
>     - symfony/symfony v3.4.13 conflicts with __root__[No version set (parsed as 1.0.0)].
>     - symfony/symfony v3.4.14 conflicts with __root__[No version set (parsed as 1.0.0)].
>     - symfony/symfony v3.4.2 conflicts with __root__[No version set (parsed as 1.0.0)].
>     - symfony/symfony v3.4.3 conflicts with __root__[No version set (parsed as 1.0.0)].
>     - symfony/symfony v3.4.4 conflicts with __root__[No version set (parsed as 1.0.0)].
>     - symfony/symfony v3.4.5 conflicts with __root__[No version set (parsed as 1.0.0)].
>     - symfony/symfony v3.4.6 conflicts with __root__[No version set (parsed as 1.0.0)].
>     - symfony/symfony v3.4.7 conflicts with __root__[No version set (parsed as 1.0.0)].
>     - symfony/symfony v3.4.8 conflicts with __root__[No version set (parsed as 1.0.0)].
>     - symfony/symfony v3.4.9 conflicts with __root__[No version set (parsed as 1.0.0)].
>     - Installation request for jorijn/ynab-bunq-connector-bundle ^1.0 -> satisfiable by jorijn/ynab-bunq-connector-bundle[v1.0.0].

And in my composer.json, I have the following:

> {
>     "Name":"paulovitorbal/bunq-ynab",
>     "type": "project",
>     "license": "proprietary",
>     "require": {
>         "php": "^7.0.8",
>         "symfony/console": "^3.4",
>         "symfony/flex": "^1.0",
>         "symfony/framework-bundle": "^3.4",
>         "symfony/lts": "^3",
>         "symfony/yaml": "^3.4"
>     },
>     "require-dev": {
>         "symfony/dotenv": "^3.4"
>     },
>     "config": {
>         "preferred-install": {
>             "*": "dist"
>         },
>         "sort-packages": true
>     },
>     "autoload": {
>         "psr-4": {
>             "App\\": "src/"
>         }
>     },
>     "autoload-dev": {
>         "psr-4": {
>             "App\\Tests\\": "tests/"
>         }
>     },
>     "scripts": {
>         "auto-scripts": {
>             "cache:clear": "symfony-cmd",
>             "assets:install %PUBLIC_DIR%": "symfony-cmd"
>         },
>         "post-install-cmd": [
>             "@auto-scripts"
>         ],
>         "post-update-cmd": [
>             "@auto-scripts"
>         ]
>     },
>     "conflict": {
>         "symfony/symfony": "*"
>     },
>     "extra": {
>         "symfony": {
>             "id": "",
>             "allow-contrib": false
>         }
>     }
> }
> 

So, I think you should change the requirements from:
`"symfony/symfony": "3.4.*",`
to
`"symfony/framework-bundle": "^3.4",`

**Comment by paulovitorbal** [comment]
I solved it by installing symfony with the following command:
`composer create-project symfony/framework-standard-edition `

**Comment by jorijn** [comment]
Glad its resolved. Hope the bundle works for you :-)

**Comment by paulovitorbal** [comment]
I make some notes about how to get it running. If you don't mind, I can open a pull request with some tutorial to help others.

**Comment by jorijn** [comment]
Sounds good! Thanks.
